# Generated by Django 3.2.6 on 2021-08-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255, verbose_name='ALIMENTOS')),
                ('qt_g', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='QT')),
                ('ptn', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='PTN')),
                ('gli', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='GLI')),
                ('lip', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='LIP')),
                ('ca', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ca')),
                ('p', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='P')),
                ('fe', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Fe')),
                ('vit_a', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='VIT-A')),
                ('tia', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='TIA')),
                ('ribo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='RIBO')),
                ('nia', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='NIA')),
                ('vit_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='VIT-C')),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='FIBRA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
