# Generated by Django 3.2.6 on 2021-08-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_auto_20210811_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthropometric',
            name='age_range',
            field=models.CharField(choices=[('A', 'Criança 0 a 5 Anos'), ('B', 'Criança 6 a 10 Anos'), ('C', 'Adolescente 11 a 19 Anos'), ('D', 'Adulto')], max_length=2, verbose_name='ESTADO'),
        ),
        migrations.DeleteModel(
            name='AgeRange',
        ),
    ]
