# Generated by Django 3.2.6 on 2021-08-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_auto_20210811_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthropometric',
            name='age_range',
            field=models.CharField(choices=[('A', 'Criança 0 a 5 Anos'), ('B', 'Criança 6 a 10 Anos'), ('C', 'Adolescente 11 a 19 Anos'), ('D', 'Adulto')], max_length=2, verbose_name='FAIXA ETÁRIA'),
        ),
        migrations.AlterField(
            model_name='anthropometric',
            name='imc',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='nutricalc',
            name='food_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.base', verbose_name='PACIENTE'),
        ),
    ]
